### ISSUE TITLE
Sporadic "VERSION_EXISTS" Error - Possible Fix?

### ISSUE THREAD

**Issue by adamgoose** [hoxton-one/deepstream.io-client-js#10] opened 2015-06-13 10:39 UTC
Occasionally, I get a "VERSION_EXISTS" error saying something like `user.1 tried to update record unread_counts.1&2 to version 3 but it already was 3`. Due to the nature of my code, this record will get updated quite frequently. I assume that this is happening because when the update is sent, the client has not yet received the updated version from, in my case, `user.2`.

Without knowing enough about how the server manages version numbers, would it be possible to handle version increments on the server side in order to prevent this? I can't see how a client jumping from version 1 to version 3 of a document could cause any serious issues if updates are processed so quickly.

> By the way, don't hate on my user ID scheme. Users are not stored in the DS Storage at all, and is only used as an identifier to the user object in my application's database.

**Comment by yasserf** [comment] 2015-06-24 12:38
Improving version conflict handling / supporting more sophisticated merge strategies is currently at the very top of our priority list. Please see #7 for updates.

**Comment by yasserf** [comment] 2015-10-01 13:13
Closing this issue as a duplicate of #7

**Closed by yasserf** 2015-10-01 13:13 UTC
